### ISSUE TITLE
There is no get_viewpoints.py under the object_level folder

### ISSUE THREAD

**Issue by bearprin** [Gorilla-Lab-SCUT/SCUTSurface-code#1]
Hi, thanks for your impressive work.

I am confused there is no get_viewpoints.py under the object_level folder, but the README.md shows I should run it first to scan the point cloud from mesh.

Could you help me?

Best,
Zi

**Comment by Huang-ZhangJin** [comment]
Thanks for your reminder. There is a little error in the README.md under the object_level folder, I have updated it.
