### ISSUE TITLE
22 evaluation data

### ISSUE THREAD

**Issue by ryamauchi** [Gorilla-Lab-SCUT/SCUTSurface-code#2]
Hello.

I am planning to evaluate my surface reconstruction method with your benchmark dataset.

You says "we randomly sample 22 synthetic surfaces of object instances" in Section 5.1, but I could not find any information on which files these 22 object instances are.

Please tell me the names of these 22 files so that I can make a fair comparison with the scores presented in your paper.

Thank you.

**Comment by Huang-ZhangJin** [comment]
Thanks for your interest!
We will continue publicizing these 22 synthetic surfaces later on our benchmark page.
