### ISSUE TITLE
The Marching cubes resolution for the implict methods (learning-based and nonlearning-based)

### ISSUE THREAD

**Issue by bearprin** [Gorilla-Lab-SCUT/SCUTSurface-code#4]
Hello, thanks for your work.

I want to evaluate my method under your benchmark.

But I do not know the marching cubes resolution used by the implicit methods, such as RIMLS, and Points2Surf.

Do you use default resolution (RIMLS: 200 in the meshlab, Points2Surf: 256 in their code) or have you adjusted it to the same one?

For fairness, I want my method to leverage the same resolution, too.

Could you tell me details about that? 

Thank you!

**Comment by Huang-ZhangJin** [comment]
Hi! Thanks for your interest!
For a fair comparison, we set the Marching Cubes resolution to 512. 
Hope it is helpful to you.
