### ISSUE TITLE
What are the noise levels for Noise.tar.gz?

### ISSUE THREAD

**Issue by trisct** [Gorilla-Lab-SCUT/SCUTSurface-code#6]
Hi, thank you for sharing this dataset!

I wonder what noise levels are used to produce Noise1, Noise2 and Noise3. From this [file](https://github.com/Gorilla-Lab-SCUT/SCUTSurface-code/blob/main/build_dataset/scan_and_synthesis/object_level/README.md), it seems that they should correspond to 0.001, 0.003 and 0.006, respectively. However, visually it appears that the noise level is actually Noise2 < Noise3 < Noise1.

It is correct that actually Noise2 -> 0.001, Noise3 -> 0.003 and Noise1 -> 0.006?

If it helps, the CRC checksum of my downloaded `Noise.tar.gz` is 37527821

**Comment by Huang-ZhangJin** [comment]
Thanks for your interest.
The corresponding noise level are: Noise1 -> 0.001, Noise2 -> 0.003 and Noise3 -> 0.006.
Please re-download the data and check it again.

**Comment by trisct** [comment]
@Huang-ZhangJin Now it appears to be Noise1 -> 0.003, Noise2 -> 0.001. Can you check again? The new CRC checksum is 1239228024
