### ISSUE TITLE
Problems downloading the data set

### ISSUE THREAD

**Issue by JoBloess** [Gorilla-Lab-SCUT/SCUTSurface-code#7]
thank you very much for sharing your work publicly!

I want to use you data and metrics on a surface reconstruction technique, however I have problems downloading your data set.
For every file larger than 3GB the download interrupts after ca 200 MB. 
I used FireFox 104.0.2 (64-Bit) on Windows 10 and I am located in Germany.
Can you verify that your links still work? or maybe upload them to another platform.

Best regards
Josua

**Comment by Huang-ZhangJin** [comment]
We have uploaded the data to Google Drive and updated the download link.
